networks:
  my-network:
    driver: bridge

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    networks:
      - my-network
    
  # backend:
  #   container_name: backend
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - mongo_db
  #   command: 'yarn dev'
  #   volumes:
  #     - ./backend:/app
  #   networks:
  #     - my-network
  #   # environment:
  #   #   - MONGO_URI=${MONGO_URI}

  # frontend:
  #   container_name: frontend
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend
  #   command: 'yarn dev'
  #   networks:
  #     - my-network