
networks:
  mynetwork:
    driver: bridge

services:
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - mynetwork
    
  backend:
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    command: 'yarn dev'
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  frontend:
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    command: 'yarn dev'
    networks:
      - mynetwork