networks:
  my-network:
    driver: bridge

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    networks:
      - my-network

  backend-service:
    container_name: backend-service
    image: node:20
    working_dir: /app/backend
    restart: always
    volumes:
      - .:/app:rw
    build: 
      context: ./backend
    ports:
      - 8010:8000
    depends_on:
      - mongo_db
    command: 'yarn dev'
    networks:
      - my-network
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo_db:${MONGO_PORT}/${MONGO_DB}?authSource=admin

  frontend-service:
    container_name: frontend-service
    image: node:20
    working_dir: /app/frontend
    restart: always
    volumes:
      - .:/app:rw
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend-service
    command: 'yarn dev'
    networks:
      - my-network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend-service
      - frontend-service
    networks:
      - my-network