networks:
  my-network:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - my-network

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    networks:
      - my-network

  backend-service:
    container_name: backend-service
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app:rw
    build: 
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - mongo_db
    command: 'yarn dev'
    networks:
      - my-network
    # environment:
    #   - MONGO_URI=${MONGO_URI}

  frontend-service:
    container_name: frontend-service
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app:rw
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend-service
    command: 'yarn dev'
    networks:
      - my-network